# Generated by Django 3.2.6 on 2021-08-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onlineMonthlySub', models.IntegerField()),
                ('onlineAnnualSub', models.IntegerField()),
                ('gymMonthlySub', models.IntegerField()),
                ('gymAnnualSub', models.IntegerField()),
            ],
        ),
    ]
