# Generated by Django 3.2.7 on 2021-09-06 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onlineMonthlySub', models.IntegerField()),
                ('onlineAnnualSub', models.IntegerField()),
                ('gymMonthlySub', models.IntegerField()),
                ('gymAnnualSub', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=200)),
                ('video_description', models.CharField(max_length=500)),
                ('video_URL', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('video_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VideoWatchTime',
            fields=[
                ('video_watch_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_watch_time', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('videoCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.videocategory')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('video_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('videoCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.videocategory')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='videoCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.videocategory'),
        ),
    ]
