# Generated by Django 3.2.6 on 2021-08-20 05:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip_address', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription', models.CharField(max_length=50)),
                ('billing_cycle_days', models.IntegerField()),
                ('gym_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=200)),
                ('video_description', models.CharField(max_length=500)),
                ('video_URL', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('video_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VideoWatchTime',
            fields=[
                ('video_watch_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_watch_time', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.customer')),
                ('videoCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.videocategory')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('video_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.customer')),
                ('videoCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.videocategory')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='videoCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.videocategory'),
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('customer_subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('auto_reccurring_subscription', models.BooleanField(default=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.customer')),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.subscription')),
            ],
        ),
    ]
