# Generated by Django 3.2.7 on 2021-09-06 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorating',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='clubApp.video'),
        ),
        migrations.AlterField(
            model_name='videowatchtime',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_times', to='clubApp.video'),
        ),
    ]
