# Generated by Django 3.2.6 on 2021-09-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_image_URL',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
