# Generated by Django 3.2.6 on 2021-08-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubApp', '0002_auto_20210820_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
