# Generated by Django 3.2.6 on 2021-08-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clubApp', '0003_alter_customer_address_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubscription',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customersubscription',
            name='subscription_id',
        ),
        migrations.AlterField(
            model_name='videorating',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='videowatchtime',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerSubscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
