# Generated by Django 3.2.7 on 2021-09-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubApp', '0004_merge_0002_changed_video_0003_auto_20210906_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videoCategory',
            new_name='video_category',
        ),
        migrations.RemoveField(
            model_name='videorating',
            name='videoCategory',
        ),
        migrations.RemoveField(
            model_name='videowatchtime',
            name='videoCategory',
        ),
    ]
