# Generated by Django 3.2.6 on 2021-09-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubApp', '0005_auto_20210909_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_rating',
            field=models.IntegerField(default=0),
        ),
    ]
