# Generated by Django 3.2.6 on 2021-09-01 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('expiry', models.DateField(default=datetime.date.today)),
                ('cvv', models.CharField(max_length=100)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='billing_cycle_days',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='gym_access',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer_id',
            field=models.ForeignKey(default='5b2fa88c-696f-4d3d-9f90-e16b6936add3', on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_choice',
            field=models.CharField(choices=[('ANNUAL_GYM', 'Annual Gym Membership'), ('MONTHLY_GYM', 'Monthly Gym Membership'), ('ANNUAL_ONLINE', 'Annual Online Membership'), ('MONTHLY_ONLINE', 'Monthly Online Membership')], default='0', max_length=30),
        ),
        migrations.DeleteModel(
            name='CustomerSubscription',
        ),
    ]
