# Generated by Django 3.2.6 on 2021-09-02 00:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('expiry', models.DateField(default=datetime.date.today)),
                ('cvv', models.CharField(max_length=100)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='billing_cycle_days',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='gym_access',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer_id',
            field=models.ForeignKey(default='c5e90f32-49e6-4622-be31-69cf4406ab98', on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_choice',
            field=models.CharField(choices=[('ANNUAL_GYM', 'Annual Gym Membership'), ('MONTHLY_GYM', 'Monthly Gym Membership'), ('ANNUAL_ONLINE', 'Annual Online Membership'), ('MONTHLY_ONLINE', 'Monthly Online Membership')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_address',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='CustomerSubscription',
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
