# Generated by Django 3.2.6 on 2021-09-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210902_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', error_messages={'required': 'We need to know what to call you, please enter your first name'}, max_length=50, null=True),
        ),
    ]
